#!/bin/sh
# This file can be used by supervisor to run command in the virtual env
# Simply copy it to an accissible place
. bqenv/bin/activate
mkdir -p /tmp/bisque-python-eggs
export PYTHON_EGG_CACHE=/tmp/bisque-python-eggs
echo "STARTING " $(date)

exec $@
