feature_list = {}

#naming convention begins with the extractor and ends with the transforms in the order stated
#
#["Extractor","transform1","transform2","length","require colored image(True/False)"]

# Chebishev Statistics Extractors
feature_list["Chebishev_Statistics"] = ["Chebyshev Coefficients","Empty Transform","Empty Transform",32,False] 
#feature_list["Chebishev_Statistics_Chebyshev"] = ["Chebyshev Coefficients","Chebyshev Transform","Empty Transform",32,False] 
#feature_list["Chebishev_Statistics_Hue_Chebyshev"] = ["Chebyshev Coefficients","Hue Transform","Chebyshev Transform",32,True] 
#feature_list["Chebishev_Statistics_Color"] = ["Chebyshev Coefficients","Color Transform","Empty Transform",32,True] 
#feature_list["Chebishev_Statistics_Edge"] = ["Chebyshev Coefficients","Edge Transform","Empty Transform",32,False] 
#feature_list["Chebishev_Statistics_Fourier"] = ["Chebyshev Coefficients","Fourier Transform","Empty Transform",32,False] 
#feature_list["Chebishev_Statistics_Edge_Fourier"] = ["Chebyshev Coefficients","Edge Transform","Fourier Transform",32,False] 
#feature_list["Chebishev_Statistics_Hue_Fourier"] = ["Chebyshev Coefficients","Hue Transform","Fourier Transform",32,True] 
#feature_list["Chebishev_Statistics_Fourier_Wavelet"] = ["Chebyshev Coefficients","Fourier Transform","Wavelet Transform",32,False] 
#feature_list["Chebishev_Statistics_Hue"] = ["Chebyshev Coefficients","Hue Transform","Empty Transform",32,True] 
#feature_list["Chebishev_Statistics_Wavelet"] = ["Chebyshev Coefficients","Wavelet Transform","Empty Transform",32,False] 
#feature_list["Chebishev_Statistics_Edge_Wavelet"] = ["Chebyshev Coefficients","Edge Transform","Wavelet Transform",32,False] 

# Chebyshev Fourier Transform Extractors
feature_list["Chebyshev_Fourier_Transform"] = ["Chebichev Fourier Transform","Empty Transform","Empty Transform",32,False]
#feature_list["Chebishev_Fourier_Transform_Chebyshev"] = ["Chebichev Fourier Transform","Chebyshev Transform","Empty Transform",32,False] 
#feature_list["Chebishev_Fourier_Transform_Hue_Chebyshev"] = ["Chebichev Fourier Transform","Hue Transform","Chebyshev Transform",32,True]
#feature_list["Chebishev_Fourier_Transform_Color"] = ["Chebichev Fourier Transform","Color Transform","Empty Transform",32,True]
#feature_list["Chebishev_Fourier_Transform_Edge"] = ["Chebichev Fourier Transform","Edge Transform","Empty Transform",32,False]
#feature_list["Chebishev_Fourier_Transform_Fourier"] = ["Chebichev Fourier Transform","Fourier Transform","Empty Transform",32,False]
#feature_list["Chebishev_Fourier_Transform_Edge_Fourier"] = ["Chebichev Fourier Transform","Edge Transform","Fourier Transform",32,False]
#feature_list["Chebishev_Fourier_Transform_Hue_Fourier"] = ["Chebichev Fourier Transform","Hue Transform","Fourier Transform",32,True]
#feature_list["Chebishev_Fourier_Transform_Fourier_Wavelet"] = ["Chebichev Fourier Transform","Fourier Transform","Wavelet Transform",32,False]
#feature_list["Chebishev_Fourier_Transform_Hue"] = ["Chebichev Fourier Transform","Hue Transform","Empty Transform",32,True]
#feature_list["Chebishev_Fourier_Transform_Wavelet"] = ["Chebichev Fourier Transform","Wavelet Transform","Empty Transform",32,False]
#feature_list["Chebishev_Fourier_Transform_Edge_Wavelet"] = ["Chebichev Fourier Transform","Edge Transform","Wavelet Transform",32,False]

#color histogram
feature_list["Color_Histogram"] = ["Color Histogram","Empty Transform","Empty Transform",20,True]

#Comb Moments Extractors
#4 orientations mean std skew kurt 3 bins each
feature_list["Comb_Moments"] = ["Comb Four Moments","Empty Transform","Empty Transform",48,False]
#feature_list["Comb_Moments_Chebyshev"] = ["Comb Four Moments","Chebyshev Transform","Empty Transform",48,False]
#feature_list["Comb_Moments_Fourier_Chebyshev"] = ["Comb Four Moments","Fourier Transform","Chebyshev Transform",48,False]
#feature_list["Comb_Moments_Hue_Fourier"] = ["Comb Four Moments","Hue Transform","Fourier Transform",48,True]
#feature_list["Comb_Moments_Wavelet_Chebyshev"] = ["Comb Four Moments","Wavelet Transform","Chebyshev Transform",48,False]
#feature_list["Comb_Moments_Color"] = ["Comb Four Moments","Color Transform","Chebyshev Transform",48,True]
#feature_list["Comb_Moments_Edge"] = ["Comb Four Moments","Edge Transform","Empty Transform",48,False]
#feature_list["Comb_Moments_Fourier"] = ["Comb Four Moments","Fourier Transform","Empty Transform",48,False]
#feature_list["Comb_Moments_Chebyshev_Fourier"] = ["Comb Four Moments","Chebyshev Transform","Fourier Transform",48,False]
#feature_list["Comb_Moments_Edge_Fourier"] = ["Comb Four Moments","Edge Transform","Fourier Transform",48,False]
#feature_list["Comb_Moments_Hue_Fourier"] = ["Comb Four Moments","Hue Transform","Fourier Transform",48,True]
#feature_list["Comb_Moments_Wavelet_Fourier"] = ["Comb Four Moments","Wavelet Transform","Fourier Transform",48,False]
#feature_list["Comb_Moments_Hue"] = ["Comb Four Moments","Hue Transform","Empty Transform",48,True]
#feature_list["Comb_Moments_Wavelet"] = ["Comb Four Moments","Wavelet Transform","Empty Transform",48,False]
#feature_list["Comb_Moments_Edge_Wavelet"] = ["Comb Four Moments","Edge Transform","Wavelet Transform",48,False]
#feature_list["Comb_Moments_Fourier_Wavelet"] = ["Comb Four Moments","Fourier Transform","Wavelet Transform",48,False]

#Edge Features Extractors
feature_list["Edge_Features"] = ["Edge Features","Empty Transform","Empty Transform",28,False]

#Fractal Extractors
feature_list["Fractal_Features"] = ["Fractal Features","Empty Transform","Empty Transform",20,False] 
#feature_list["Fractal_Features_Chebyshev"] = ["Fractal Features","Chebyshev Transform","Empty Transform",20,False] 
#feature_list["Fractal_Features_Fourier_Chebyshev"] = ["Fractal Features","Fourier Transform","Chebyshev Transform",20,False] 
#feature_list["Fractal_Features_Hue_Chebyshev"] = ["Fractal Features","Hue Transform","Chebyshev Transform",20,True]
#feature_list["Fractal_Features_Wavelet_Chebyshev"] = ["Fractal Features","Wavelet Transform","Chebyshev Transform",20,False] 
#feature_list["Fractal_Features_Color"] = ["Fractal Features","Color Transform","Empty Transform",20,True] 
#feature_list["Fractal_Features_Edge"] = ["Fractal Features","Edge Transform","Empty Transform",20,False] 
#feature_list["Fractal_Features_Fourier"] = ["Fractal Features","Fourier Transform","Empty Transform",20,False] 
#feature_list["Fractal_Features_Chebyshev_Fourier"] = ["Fractal Features","Chebyshev Transform","Fourier Transform",20,False] 
#feature_list["Fractal_Features_Edge_Fourier"] = ["Fractal Features","Edge Transform","Fourier Transform",20,False] 
#feature_list["Fractal_Features_Hue_Fourier"] = ["Fractal Features","Hue Transform","Fourier Transform",20,True] 
#feature_list["Fractal_Features_Wavelet_Fourier"] = ["Fractal Features","Wavelet Transform","Fourier Transform",20,False] 
#feature_list["Fractal_Features_Hue"] = ["Fractal Features","Hue Transform","Empty Transform",20,True] 
#feature_list["Fractal_Features_Wavelet"] = ["Fractal Features","Wavelet Transform","Empty Transform",20,False] 
#feature_list["Fractal_Features_Edge_Wavelet"] = ["Fractal Features","Edge Transform","Wavelet Transform",20,False] 
#feature_list["Fractal_Features_Fourier_Wavelet"] = ["Fractal Features","Fourier Transform","Wavelet Transform",20,False] 

#Gini Coeffivient
feature_list["Gini_Coefficient"] = ["Gini Coefficient","Empty Transform","Empty Transform",1,False] 
#feature_list["Gini_Coefficient_Fourier"] = ["Gini Coefficient","Fourier Transform","Empty Transform",1,False] 
#feature_list["Gini_Coefficient_Wavelet"] = ["Gini Coefficient","Wavelet Transform","Empty Transform",1,False] 
#feature_list["Gini_Coefficient_Chebyshev"] = ["Gini Coefficient","Chebyshev Transform","Empty Transform",1,False] 
#feature_list["Gini_Coefficient_Fourier_Chebyshev"] = ["Gini Coefficient","Fourier Transform","Chebyshev Transform",1,False] 
#feature_list["Gini_Coefficient_Fourier_Wavelet"] = ["Gini Coefficient","Fourier Transform","Wavelet Transform",1,False] 
#feature_list["Gini_Coefficient_Wavelet_Fourier"] = ["Gini Coefficient","Wavelet Transform","Fourier Transform",1,False]
#feature_list["Gini_Coefficient_Chebyshev_Fourier"] = ["Gini Coefficient","Chebyshev Transform","Fourier Transform",1,False]
#feature_list["Gini_Coefficient_Wavelet_Chebyshev"] = ["Gini Coefficient","Wavelet Transform","Chebyshev Transform",1,False]
#feature_list["Gini_Coefficient_Edge"] = ["Gini Coefficient","Edge Transform","Empty Transform",1,False]
#feature_list["Gini_Coefficient_Fourier_Edge"] = ["Gini Coefficient","Edge Transform","Fourier Transform",1,False]
#feature_list["Gini_Coefficient_Wavelet_Edge"] = ["Gini Coefficient","Edge Transform","Wavelet Transform",1,False]

#Gabor Textures
feature_list["Gabor_Textures"] = ["Gabor Textures","Empty Transform","Empty Transform",7,False] 

#Haralick Textures
feature_list["Haralick_Textures"] = ["Haralick Texture","Empty Transform","Empty Transform",28,False] 
#feature_list["Haralick_Textures_Chebyshev"] = ["Haralick Texture","Chebyshev Transform","Empty Transform",28,False] 
#feature_list["Haralick_Textures_Fourier_Chebyshev"] = ["Haralick Texture","Fourier Transform","Chebyshev Transform",28,False] 
#feature_list["Haralick_Textures_Hue_Chebyshev"] = ["Haralick Texture","Hue Transform","Chebyshev Transform",28,True] 
#feature_list["Haralick_Textures_Wavelet_Chebyshev"] = ["Haralick Texture","Wavelet Transform","Chebyshev Transform",28,False]
#feature_list["Haralick_Textures_Color"] = ["Haralick Texture","Color Transform","Empty Transform",28,True]
#feature_list["Haralick_Textures_Edge"] = ["Haralick Texture","Edge Transform","Empty Transform",28,False]
#feature_list["Haralick_Textures_Fourier"] = ["Haralick Texture","Fourier Transform","Empty Transform",28,False]
#feature_list["Haralick_Textures_Chebyshev_Fourier"] = ["Haralick Texture","Chebyshev Transform","Fourier Transform",28,False]
#feature_list["Haralick_Textures_Edge_Fourier"] = ["Haralick Texture","Edge Transform","Fourier Transform",28,False]
#feature_list["Haralick_Textures_Hue_Fourier"] = ["Haralick Texture","Hue Transform","Fourier Transform",28,True]
#feature_list["Haralick_Textures_Wavelet_Fourier"] = ["Haralick Texture","Wavelet Transform","Fourier Transform",28,False]
#feature_list["Haralick_Textures_Hue"] = ["Haralick Texture","Hue Transform","Empty Transform",28,True]
#feature_list["Haralick_Textures_Wavelet"] = ["Haralick Texture","Wavelet Transform","Empty Transform",28,False]
#feature_list["Haralick_Textures_Edge_Wavelet"] = ["Haralick Texture","Edge Transform","Wavelet Transform",28,False]
#feature_list["Haralick_Textures_Fourier_Wavelet"] = ["Haralick Texture","Fourier Transform","Wavelet Transform",28,False]

#Multiscale Historgram
feature_list["Multiscale_Historgram"] = ["Multi Scale Histogram","Empty Transform","Empty Transform",24,False]
#feature_list["Multiscale_Historgram_Chebyshev"] = ["Multi Scale Histogram","Chebyshev Transform","Empty Transform",24,False]
#feature_list["Multiscale_Historgram_Fourier_Chebyshev"] = ["Multi Scale Histogram","Fourier Transform","Chebyshev Transform",24,False]
#feature_list["Multiscale_Historgram_Hue_Chebyshev"] = ["Multi Scale Histogram","Hue Transform","Chebyshev Transform",24,True]
#feature_list["Multiscale_Historgram_Wavelet_Chebyshev"] = ["Multi Scale Histogram","Wavelet Transform","Chebyshev Transform",24,False]
#feature_list["Multiscale_Historgram_Color"] = ["Multi Scale Histogram","Color Transform","Empty Transform",24,True]
#feature_list["Multiscale_Historgram_Edge"] = ["Multi Scale Histogram","Edge Transform","Empty Transform",24,False]
#feature_list["Multiscale_Historgram_Fourier"] = ["Multi Scale Histogram","Fourier Transform","Empty Transform",24,False]
#feature_list["Multiscale_Historgram_Chebyshev_Fourier"] = ["Multi Scale Histogram","Chebyshev Transform","Fourier Transform",24,False]
#feature_list["Multiscale_Historgram_Edge_Fourier"] = ["Multi Scale Histogram","Edge Transform","Fourier Transform",24,False]
#feature_list["Multiscale_Historgram_Hue_Fourier"] = ["Multi Scale Histogram","Hue Transform","Fourier Transform",24,True]
#feature_list["Multiscale_Historgram_Wavelet_Fourier"] = ["Multi Scale Histogram","Wavelet Transform","Fourier Transform",24,False]
#feature_list["Multiscale_Historgram_Hue"] = ["Multi Scale Histogram","Hue Transform","Empty Transform",24,True]
#feature_list["Multiscale_Historgram_Wavelet"] = ["Multi Scale Histogram","Wavelet Transform","Empty Transform",24,False]
#feature_list["Multiscale_Historgram_Edge_Wavelet"]  = ["Multi Scale Histogram","Edge Transform","Wavelet Transform",24,False]
#feature_list["Multiscale_Historgram_Fourier_Wavelet"] = ["Multi Scale Histogram","Fourier Transform","Wavelet Transform",24,False]

#Object Feature
feature_list["Object_Feature"] = ["Object Features","Empty Transform","Empty Transform",34,False]

#Pixel Intensity Statistics
#mean median std min max
feature_list["Pixel_Intensity_Statistics"] = ["Pixel Intensity Statistics","Empty Transform","Empty Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Chebyshev"] = ["Pixel Intensity Statistics","Chebyshev Transform","Empty Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Fourier_Chebyshev"] = ["Pixel Intensity Statistics","Fourier Transform","Chebyshev Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Hue_Chebyshev"] = ["Pixel Intensity Statistics","Hue Transform","Chebyshev Transform",5,True]
#feature_list["Pixel_Intensity_Statistics_Wavelet_Chebyshev"] = ["Pixel Intensity Statistics","Wavelet Transform","Chebyshev Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Color"] = ["Pixel Intensity Statistics","Color Transform","Empty Transform",5,True]
#feature_list["Pixel_Intensity_Statistics_Edge"] = ["Pixel Intensity Statistics","Edge Transform","Empty Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Fourier"] = ["Pixel Intensity Statistics","Fourier Transform","Empty Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Chebyshev_Fourier"] = ["Pixel Intensity Statistics","Chebyshev Transform","Fourier Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Edge_Fourier"] = ["Pixel Intensity Statistics","Edge Transform","Fourier Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Hue_Fourier"] = ["Pixel Intensity Statistics","Hue Transform","Fourier Transform",5,True]
#feature_list["Pixel_Intensity_Statistics_Wavelet_Fourier"] = ["Pixel Intensity Statistics","Wavelet Transform","Fourier Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Hue"] = ["Pixel Intensity Statistics","Hue Transform","Empty Transform",5,True]
#feature_list["Pixel_Intensity_Statistics_Wavelet"] = ["Pixel Intensity Statistics","Wavelet Transform","Empty Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Edge_Wavelet"] = ["Pixel Intensity Statistics","Edge Transform","Wavelet Transform",5,False]
#feature_list["Pixel_Intensity_Statistics_Fourier_Wavelet"] = ["Pixel Intensity Statistics","Fourier Transform","Wavelet Transform",5,False]

#Radon Coefficients
feature_list["Radon_Coefficients"] = ["Radon Transform","Empty Transform","Empty Transform",12,False]
#feature_list["Radon_Coefficients_Chebyshev"] = ["Radon Transform","Chebyshev Transform","Empty Transform",12,False]
#feature_list["Radon_Coefficients_Fourier_Chebyshev"] = ["Radon Transform","Fourier Transform","Chebyshev Transform",12,False]
#feature_list["Radon_Coefficients_Hue_Chebyshev"] = ["Radon Transform","Hue Transform","Chebyshev Transform",12,True]
#feature_list["Radon_Coefficients_Wavelet_Chebyshev"] = ["Radon Transform","Wavelet Transform","Chebyshev Transform",12,False]
#feature_list["Radon_Coefficients_Color"] = ["Radon Transform","Color Transform","Empty Transform",12,True]
#feature_list["Radon_Coefficients_Edge"] = ["Radon Transform","Edge Transform","Empty Transform",12,False]
#feature_list["Radon_Coefficients_Fourier"] = ["Radon Transform","Fourier Transform","Empty Transform",12,False]
#feature_list["Radon_Coefficients_Chebyshev_Fourier"] = ["Radon Transform","Chebyshev Transform","Fourier Transform",12,False]
#feature_list["Radon_Coefficients_Edge_Fourier"] = ["Radon Transform","Edge Transform","Fourier Transform",12,False]
#feature_list["Radon_Coefficients_Hue_Fourier"] = ["Radon Transform","Hue Transform","Fourier Transform",12,True]
#feature_list["Radon_Coefficients_Wavelet_Fourier"] = ["Radon Transform","Wavelet Transform","Fourier Transform",12,False]
#feature_list["Radon_Coefficients_Hue"] = ["Radon Transform","Hue Transform","Empty Transform",12,True]
#feature_list["Radon_Coefficients_Wavelet"] = ["Radon Transform","Wavelet Transform","Empty Transform",12,False]
#feature_list["Radon_Coefficients_Edge_Wavelet"] = ["Radon Transform","Edge Transform","Wavelet Transform",12,False]
#feature_list["Radon_Coefficients_Fourier_Wavelet"] = ["Radon Transform","Fourier Transform","Wavelet Transform",12,False]


#Tamura Textures
feature_list["Tamura_Textures"] = ["Tamura Texture","Empty Transform","Empty Transform",6,False]
#feature_list["Tamura_Textures_Chebyshev"] = ["Tamura Texture","Chebyshev Transform","Empty Transform",6,False]
#feature_list["Tamura_Textures_Fourier_Chebyshev"] = ["Tamura Texture","Fourier Transform","Chebyshev Transform",6,False]
#feature_list["Tamura_Textures_Hue_Chebyshev"] = ["Tamura Texture","Hue Transform","Chebyshev Transform",6,True]
#feature_list["Tamura_Textures_Wavelet_Chebyshev"] = ["Tamura Texture","Wavelet Transform","Chebyshev Transform",6,False]
#feature_list["Tamura_Textures_Color"] = ["Tamura Texture","Color Transform","Empty Transform",6,True]
#feature_list["Tamura_Textures_Edge"] = ["Tamura Texture","Edge Transform","Empty Transform",6,False]
#feature_list["Tamura_Textures_Fourier"] = ["Tamura Texture","Fourier Transform","Empty Transform",6,False]
#feature_list["Tamura_Textures_Chebyshev_Fourier"] = ["Tamura Texture","Chebyshev Transform","Fourier Transform",6,False]
#feature_list["Tamura_Textures_Edge_Fourier"] = ["Tamura Texture","Edge Transform","Fourier Transform",6,False]
#feature_list["Tamura_Textures_Hue_Fourier"] = ["Tamura Texture","Hue Transform","Fourier Transform",6,True]
#feature_list["Tamura_Textures_Wavelet_Fourier"] = ["Tamura Texture","Wavelet Transform","Fourier Transform",6,False]
#feature_list["Tamura_Textures_Hue"] = ["Tamura Texture","Hue Transform","Empty Transform",6,True]
#feature_list["Tamura_Textures_Wavelet"] = ["Tamura Texture","Wavelet Transform","Empty Transform",6,False]
#feature_list["Tamura_Textures_Edge_Wavelet"] = ["Tamura Texture","Edge Transform","Wavelet Transform",6,False]
#feature_list["Tamura_Textures_Fourier_Wavelet"] = ["Tamura Texture","Fourier Transform","Wavelet Transform",6,False]

#Zernike Coeffivients
feature_list["Zernike_Coefficients"] = ["Zernike Coefficients","Empty Transform","Empty Transform",72,False]
#feature_list["Zernike_Coefficients_Chebyshev"] = ["Zernike Coefficients","Chebyshev Transform","Empty Transform",72,False]
#feature_list["Zernike_Coefficients_Hue_Chebyshev"] = ["Zernike Coefficients","Hue Transform","Chebyshev Transform",72,True]
#feature_list["Zernike_Coefficients_Color"] = ["Zernike Coefficients","Color Transform","Empty Transform",72,True]
#feature_list["Zernike_Coefficients_Edge"] = ["Zernike Coefficients","Edge Transform","Empty Transform",72,False]
#feature_list["Zernike_Coefficients_Fourier"] = ["Zernike Coefficients","Fourier Transform","Empty Transform",72,False]
#feature_list["Zernike_Coefficients_Edge_Fourier"] = ["Zernike Coefficients","Edge Transform","Fourier Transform",72,False]
#feature_list["Zernike_Coefficients_Hue_Fourier"] = ["Zernike Coefficients","Hue Transform","Fourier Transform",72,True]
#feature_list["Zernike_Coefficients_Wavelet_Fourier"] = ["Zernike Coefficients","Wavelet Transform","Fourier Transform",72,False]
#feature_list["Zernike_Coefficients_Hue"] = ["Zernike Coefficients","Hue Transform","Empty Transform",72,True]
#feature_list["Zernike_Coefficients_Wavelet"] = ["Zernike Coefficients","Wavelet Transform","Empty Transform",72,False]
#feature_list["Zernike_Coefficients_Edge_Wavelet"] = ["Zernike Coefficients","Edge Transform","Wavelet Transform",72,False]

