feature_list = {}

#naming convention begins with the extractor and ends with the transforms in the order stated
#
#["Extractor","transform1","transform2","length","require colored image(True/False)","required colored image into the transform"]

# Chebishev Statistics Extractors
feature_list["Chebishev_Statistics"] = ["Chebyshev Coefficients","Empty Transform","Empty Transform",32,False,False]
feature_list["Chebishev_Statistics_Chebyshev"] = ["Chebyshev Coefficients","chebyshev","Empty Transform",32,False,False]
feature_list["Chebishev_Statistics_Hue_Chebyshev"] = ["Chebyshev Coefficients","Hue Transform","chebyshev",32,True,False]
feature_list["Chebishev_Statistics_Color"] = ["Chebyshev Coefficients","wndchrmcolor","Empty Transform",32,True,False]
feature_list["Chebishev_Statistics_Edge"] = ["Chebyshev Coefficients","edge","Empty Transform",32,False,False]
feature_list["Chebishev_Statistics_Fourier"] = ["Chebyshev Coefficients","fourier","Empty Transform",32,False,False]
feature_list["Chebishev_Statistics_Edge_Fourier"] = ["Chebyshev Coefficients","edge","fourier",32,False,False]
feature_list["Chebishev_Statistics_Hue_Fourier"] = ["Chebyshev Coefficients","Hue Transform","fourier",32,True,False]
feature_list["Chebishev_Statistics_Fourier_Wavelet"] = ["Chebyshev Coefficients","fourier","wavelet",32,False,False]
feature_list["Chebishev_Statistics_Hue"] = ["Chebyshev Coefficients","Hue Transform","Empty Transform",32,True,False]
feature_list["Chebishev_Statistics_Wavelet"] = ["Chebyshev Coefficients","wavelet","Empty Transform",32,False,False] 
feature_list["Chebishev_Statistics_Edge_Wavelet"] = ["Chebyshev Coefficients","edge","wavelet",32,False,False]

# Chebyshev Fourier Transform Extractors
feature_list["Chebyshev_Fourier_Transform"] = ["Chebichev Fourier Transform","Empty Transform","Empty Transform",32,False,False]
feature_list["Chebishev_Fourier_Transform_Chebyshev"] = ["Chebichev Fourier Transform","chebyshev","Empty Transform",32,False,False] 
feature_list["Chebishev_Fourier_Transform_Hue_Chebyshev"] = ["Chebichev Fourier Transform","Hue Transform","chebyshev",32,True,False]
feature_list["Chebishev_Fourier_Transform_Color"] = ["Chebichev Fourier Transform","wndchrmcolor","Empty Transform",32,True,False]
feature_list["Chebishev_Fourier_Transform_Edge"] = ["Chebichev Fourier Transform","edge","Empty Transform",32,False,False]
feature_list["Chebishev_Fourier_Transform_Fourier"] = ["Chebichev Fourier Transform","fourier","Empty Transform",32,False,False]
feature_list["Chebishev_Fourier_Transform_Edge_Fourier"] = ["Chebichev Fourier Transform","edge","fourier",32,False,False]
feature_list["Chebishev_Fourier_Transform_Hue_Fourier"] = ["Chebichev Fourier Transform","Hue Transform","fourier",32,True,False]
feature_list["Chebishev_Fourier_Transform_Fourier_Wavelet"] = ["Chebichev Fourier Transform","fourier","wavelet",32,False,False]
feature_list["Chebishev_Fourier_Transform_Hue"] = ["Chebichev Fourier Transform","Hue Transform","Empty Transform",32,True,False]
feature_list["Chebishev_Fourier_Transform_Wavelet"] = ["Chebichev Fourier Transform","wavelet","Empty Transform",32,False,False]
feature_list["Chebishev_Fourier_Transform_Edge_Wavelet"] = ["Chebichev Fourier Transform","edge","wavelet",32,False,False]

#color histogram
feature_list["Color_Histogram"] = ["Color Histogram","Empty Transform","Empty Transform",20,True,True]

#Comb Moments Extractors
#4 orientations mean std skew kurt 3 bins each
feature_list["Comb_Moments"] = ["Comb Four Moments","Empty Transform","Empty Transform",48,False,False]
feature_list["Comb_Moments_Chebyshev"] = ["Comb Four Moments","chebyshev","Empty Transform",48,False,False]
feature_list["Comb_Moments_Fourier_Chebyshev"] = ["Comb Four Moments","fourier","chebyshev",48,False,False]
feature_list["Comb_Moments_Hue_Fourier"] = ["Comb Four Moments","Hue Transform","fourier",48,True,False]
feature_list["Comb_Moments_Wavelet_Chebyshev"] = ["Comb Four Moments","wavelet","chebyshev",48,False,False]
feature_list["Comb_Moments_Color"] = ["Comb Four Moments","wndchrmcolor","chebyshev",48,True,False]
feature_list["Comb_Moments_Edge"] = ["Comb Four Moments","edge","Empty Transform",48,False,False]
feature_list["Comb_Moments_Fourier"] = ["Comb Four Moments","fourier","Empty Transform",48,False,False]
feature_list["Comb_Moments_Chebyshev_Fourier"] = ["Comb Four Moments","chebyshev","fourier",48,False,False]
feature_list["Comb_Moments_Edge_Fourier"] = ["Comb Four Moments","edge","fourier",48,False,False]
feature_list["Comb_Moments_Hue_Fourier"] = ["Comb Four Moments","Hue Transform","fourier",48,True,False]
feature_list["Comb_Moments_Wavelet_Fourier"] = ["Comb Four Moments","wavelet","fourier",48,False,False]
feature_list["Comb_Moments_Hue"] = ["Comb Four Moments","Hue Transform","Empty Transform",48,True,False]
feature_list["Comb_Moments_Wavelet"] = ["Comb Four Moments","wavelet","Empty Transform",48,False,False]
feature_list["Comb_Moments_Edge_Wavelet"] = ["Comb Four Moments","edge","wavelet",48,False,False]
feature_list["Comb_Moments_Fourier_Wavelet"] = ["Comb Four Moments","fourier","wavelet",48,False,False]

#Edge Features Extractors
feature_list["Edge_Features"] = ["Edge Features","Empty Transform","Empty Transform",28,False,False]

#Fractal Extractors
feature_list["Fractal_Features"] = ["Fractal Features","Empty Transform","Empty Transform",20,False,False] 
feature_list["Fractal_Features_Chebyshev"] = ["Fractal Features","chebyshev","Empty Transform",20,False,False] 
feature_list["Fractal_Features_Fourier_Chebyshev"] = ["Fractal Features","fourier","chebyshev",20,False,False] 
feature_list["Fractal_Features_Hue_Chebyshev"] = ["Fractal Features","Hue Transform","chebyshev",20,True,False]
feature_list["Fractal_Features_Wavelet_Chebyshev"] = ["Fractal Features","wavelet","chebyshev",20,False,False] 
feature_list["Fractal_Features_Color"] = ["Fractal Features","wndchrmcolor","Empty Transform",20,True,False] 
feature_list["Fractal_Features_Edge"] = ["Fractal Features","edge","Empty Transform",20,False,False] 
feature_list["Fractal_Features_Fourier"] = ["Fractal Features","fourier","Empty Transform",20,False,False] 
feature_list["Fractal_Features_Chebyshev_Fourier"] = ["Fractal Features","chebyshev","fourier",20,False,False] 
feature_list["Fractal_Features_Edge_Fourier"] = ["Fractal Features","edge","fourier",20,False,False] 
feature_list["Fractal_Features_Hue_Fourier"] = ["Fractal Features","Hue Transform","fourier",20,True,False] 
feature_list["Fractal_Features_Wavelet_Fourier"] = ["Fractal Features","wavelet","fourier",20,False,False] 
feature_list["Fractal_Features_Hue"] = ["Fractal Features","Hue Transform","Empty Transform",20,True,False] 
feature_list["Fractal_Features_Wavelet"] = ["Fractal Features","wavelet","Empty Transform",20,False,False] 
feature_list["Fractal_Features_Edge_Wavelet"] = ["Fractal Features","edge","wavelet",20,False,False] 
feature_list["Fractal_Features_Fourier_Wavelet"] = ["Fractal Features","fourier","wavelet",20,False,False] 

#Gini Coeffivient
feature_list["Gini_Coefficient"] = ["Gini Coefficient","Empty Transform","Empty Transform",1,False,False] 
feature_list["Gini_Coefficient_Fourier"] = ["Gini Coefficient","fourier","Empty Transform",1,False,False] 
feature_list["Gini_Coefficient_Wavelet"] = ["Gini Coefficient","wavelet","Empty Transform",1,False,False] 
feature_list["Gini_Coefficient_Chebyshev"] = ["Gini Coefficient","chebyshev","Empty Transform",1,False,False] 
feature_list["Gini_Coefficient_Fourier_Chebyshev"] = ["Gini Coefficient","fourier","chebyshev",1,False,False] 
feature_list["Gini_Coefficient_Fourier_Wavelet"] = ["Gini Coefficient","fourier","wavelet",1,False,False] 
feature_list["Gini_Coefficient_Wavelet_Fourier"] = ["Gini Coefficient","wavelet","fourier",1,False,False]
feature_list["Gini_Coefficient_Chebyshev_Fourier"] = ["Gini Coefficient","chebyshev","fourier",1,False,False]
feature_list["Gini_Coefficient_Wavelet_Chebyshev"] = ["Gini Coefficient","wavelet","chebyshev",1,False,False]
feature_list["Gini_Coefficient_Edge"] = ["Gini Coefficient","edge","Empty Transform",1,False,False]
feature_list["Gini_Coefficient_Fourier_Edge"] = ["Gini Coefficient","edge","fourier",1,False,False]
feature_list["Gini_Coefficient_Wavelet_Edge"] = ["Gini Coefficient","edge","wavelet",1,False,False]

#Gabor Textures
feature_list["Gabor_Textures"] = ["Gabor Textures","Empty Transform","Empty Transform",7,False,False] 

#Haralick Textures
feature_list["Haralick_Textures"] = ["Haralick Texture","Empty Transform","Empty Transform",28,False,False] 
feature_list["Haralick_Textures_Chebyshev"] = ["Haralick Texture","chebyshev","Empty Transform",28,False,False] 
feature_list["Haralick_Textures_Fourier_Chebyshev"] = ["Haralick Texture","fourier","chebyshev",28,False,False] 
feature_list["Haralick_Textures_Hue_Chebyshev"] = ["Haralick Texture","Hue Transform","chebyshev",28,True,False] 
feature_list["Haralick_Textures_Wavelet_Chebyshev"] = ["Haralick Texture","wavelet","chebyshev",28,False,False]
feature_list["Haralick_Textures_Color"] = ["Haralick Texture","wndchrmcolor","Empty Transform",28,True,False]
feature_list["Haralick_Textures_Edge"] = ["Haralick Texture","edge","Empty Transform",28,False,False]
feature_list["Haralick_Textures_Fourier"] = ["Haralick Texture","fourier","Empty Transform",28,False,False]
feature_list["Haralick_Textures_Chebyshev_Fourier"] = ["Haralick Texture","chebyshev","fourier",28,False,False]
feature_list["Haralick_Textures_Edge_Fourier"] = ["Haralick Texture","edge","fourier",28,False,False]
feature_list["Haralick_Textures_Hue_Fourier"] = ["Haralick Texture","Hue Transform","fourier",28,True,False]
feature_list["Haralick_Textures_Wavelet_Fourier"] = ["Haralick Texture","wavelet","fourier",28,False,False]
feature_list["Haralick_Textures_Hue"] = ["Haralick Texture","Hue Transform","Empty Transform",28,True,False]
feature_list["Haralick_Textures_Wavelet"] = ["Haralick Texture","wavelet","Empty Transform",28,False,False]
feature_list["Haralick_Textures_Edge_Wavelet"] = ["Haralick Texture","edge","wavelet",28,False,False]
feature_list["Haralick_Textures_Fourier_Wavelet"] = ["Haralick Texture","fourier","wavelet",28,False,False]

#Multiscale Historgram
feature_list["Multiscale_Historgram"] = ["Multi Scale Histogram","Empty Transform","Empty Transform",24,False,False]
feature_list["Multiscale_Historgram_Chebyshev"] = ["Multi Scale Histogram","chebyshev","Empty Transform",24,False,False]
feature_list["Multiscale_Historgram_Fourier_Chebyshev"] = ["Multi Scale Histogram","fourier","chebyshev",24,False,False]
feature_list["Multiscale_Historgram_Hue_Chebyshev"] = ["Multi Scale Histogram","Hue Transform","chebyshev",24,True,False]
feature_list["Multiscale_Historgram_Wavelet_Chebyshev"] = ["Multi Scale Histogram","wavelet","chebyshev",24,False,False]
feature_list["Multiscale_Historgram_Color"] = ["Multi Scale Histogram","wndchrmcolor","Empty Transform",24,True,False]
feature_list["Multiscale_Historgram_Edge"] = ["Multi Scale Histogram","edge","Empty Transform",24,False,False]
feature_list["Multiscale_Historgram_Fourier"] = ["Multi Scale Histogram","fourier","Empty Transform",24,False,False]
feature_list["Multiscale_Historgram_Chebyshev_Fourier"] = ["Multi Scale Histogram","chebyshev","fourier",24,False,False]
feature_list["Multiscale_Historgram_Edge_Fourier"] = ["Multi Scale Histogram","edge","fourier",24,False,False]
feature_list["Multiscale_Historgram_Hue_Fourier"] = ["Multi Scale Histogram","Hue Transform","fourier",24,True,False]
feature_list["Multiscale_Historgram_Wavelet_Fourier"] = ["Multi Scale Histogram","wavelet","fourier",24,False,False]
feature_list["Multiscale_Historgram_Hue"] = ["Multi Scale Histogram","Hue Transform","Empty Transform",24,True,False]
feature_list["Multiscale_Historgram_Wavelet"] = ["Multi Scale Histogram","wavelet","Empty Transform",24,False,False]
feature_list["Multiscale_Historgram_Edge_Wavelet"]  = ["Multi Scale Histogram","edge","wavelet",24,False,False]
feature_list["Multiscale_Historgram_Fourier_Wavelet"] = ["Multi Scale Histogram","fourier","wavelet",24,False,False]

#Object Feature
feature_list["Object_Feature"] = ["Object Features","Empty Transform","Empty Transform",34,False,False]

#Pixel Intensity Statistics
#mean median std min max
feature_list["Pixel_Intensity_Statistics"] = ["Pixel Intensity Statistics","Empty Transform","Empty Transform",5,False,False]
feature_list["Pixel_Intensity_Statistics_Chebyshev"] = ["Pixel Intensity Statistics","chebyshev","Empty Transform",5,False,False]
feature_list["Pixel_Intensity_Statistics_Fourier_Chebyshev"] = ["Pixel Intensity Statistics","fourier","chebyshev",5,False,False]
feature_list["Pixel_Intensity_Statistics_Hue_Chebyshev"] = ["Pixel Intensity Statistics","Hue Transform","chebyshev",5,True,False]
feature_list["Pixel_Intensity_Statistics_Wavelet_Chebyshev"] = ["Pixel Intensity Statistics","wavelet","chebyshev",5,False,False]
feature_list["Pixel_Intensity_Statistics_Color"] = ["Pixel Intensity Statistics","wndchrmcolor","Empty Transform",5,True,False]
feature_list["Pixel_Intensity_Statistics_Edge"] = ["Pixel Intensity Statistics","edge","Empty Transform",5,False,False]
feature_list["Pixel_Intensity_Statistics_Fourier"] = ["Pixel Intensity Statistics","fourier","Empty Transform",5,False,False]
feature_list["Pixel_Intensity_Statistics_Chebyshev_Fourier"] = ["Pixel Intensity Statistics","chebyshev","fourier",5,False,False]
feature_list["Pixel_Intensity_Statistics_Edge_Fourier"] = ["Pixel Intensity Statistics","edge","fourier",5,False,False]
feature_list["Pixel_Intensity_Statistics_Hue_Fourier"] = ["Pixel Intensity Statistics","Hue Transform","fourier",5,True,False]
feature_list["Pixel_Intensity_Statistics_Wavelet_Fourier"] = ["Pixel Intensity Statistics","wavelet","fourier",5,False,False]
feature_list["Pixel_Intensity_Statistics_Hue"] = ["Pixel Intensity Statistics","Hue Transform","Empty Transform",5,True,False]
feature_list["Pixel_Intensity_Statistics_Wavelet"] = ["Pixel Intensity Statistics","wavelet","Empty Transform",5,False,False]
feature_list["Pixel_Intensity_Statistics_Edge_Wavelet"] = ["Pixel Intensity Statistics","edge","wavelet",5,False,False]
feature_list["Pixel_Intensity_Statistics_Fourier_Wavelet"] = ["Pixel Intensity Statistics","fourier","wavelet",5,False,False]

#Radon Coefficients
feature_list["Radon_Coefficients"] = ["Radon Transform","Empty Transform","Empty Transform",12,False,False]
feature_list["Radon_Coefficients_Chebyshev"] = ["Radon Transform","chebyshev","Empty Transform",12,False,False]
feature_list["Radon_Coefficients_Fourier_Chebyshev"] = ["Radon Transform","fourier","chebyshev",12,False,False]
feature_list["Radon_Coefficients_Hue_Chebyshev"] = ["Radon Transform","Hue Transform","chebyshev",12,True,False]
feature_list["Radon_Coefficients_Wavelet_Chebyshev"] = ["Radon Transform","wavelet","chebyshev",12,False,False]
feature_list["Radon_Coefficients_Color"] = ["Radon Transform","wndchrmcolor","Empty Transform",12,True,False]
feature_list["Radon_Coefficients_Edge"] = ["Radon Transform","edge","Empty Transform",12,False,False]
feature_list["Radon_Coefficients_Fourier"] = ["Radon Transform","fourier","Empty Transform",12,False,False]
feature_list["Radon_Coefficients_Chebyshev_Fourier"] = ["Radon Transform","chebyshev","fourier",12,False,False]
feature_list["Radon_Coefficients_Edge_Fourier"] = ["Radon Transform","edge","fourier",12,False,False]
feature_list["Radon_Coefficients_Hue_Fourier"] = ["Radon Transform","Hue Transform","fourier",12,True,False]
feature_list["Radon_Coefficients_Wavelet_Fourier"] = ["Radon Transform","wavelet","fourier",12,False,False]
feature_list["Radon_Coefficients_Hue"] = ["Radon Transform","Hue Transform","Empty Transform",12,True,False]
feature_list["Radon_Coefficients_Wavelet"] = ["Radon Transform","wavelet","Empty Transform",12,False,False]
feature_list["Radon_Coefficients_Edge_Wavelet"] = ["Radon Transform","edge","wavelet",12,False,False]
feature_list["Radon_Coefficients_Fourier_Wavelet"] = ["Radon Transform","fourier","wavelet",12,False,False]


#Tamura Textures
feature_list["Tamura_Textures"] = ["Tamura Texture","Empty Transform","Empty Transform",6,False,False]
feature_list["Tamura_Textures_Chebyshev"] = ["Tamura Texture","chebyshev","Empty Transform",6,False,False]
feature_list["Tamura_Textures_Fourier_Chebyshev"] = ["Tamura Texture","fourier","chebyshev",6,False,False]
feature_list["Tamura_Textures_Hue_Chebyshev"] = ["Tamura Texture","Hue Transform","chebyshev",6,True,False]
feature_list["Tamura_Textures_Wavelet_Chebyshev"] = ["Tamura Texture","wavelet","chebyshev",6,False,False]
feature_list["Tamura_Textures_Color"] = ["Tamura Texture","wndchrmcolor","Empty Transform",6,True,False]
feature_list["Tamura_Textures_Edge"] = ["Tamura Texture","edge","Empty Transform",6,False,False]
feature_list["Tamura_Textures_Fourier"] = ["Tamura Texture","fourier","Empty Transform",6,False,False]
feature_list["Tamura_Textures_Chebyshev_Fourier"] = ["Tamura Texture","chebyshev","fourier",6,False,False]
feature_list["Tamura_Textures_Edge_Fourier"] = ["Tamura Texture","edge","fourier",6,False,False]
feature_list["Tamura_Textures_Hue_Fourier"] = ["Tamura Texture","Hue Transform","fourier",6,True,False]
feature_list["Tamura_Textures_Wavelet_Fourier"] = ["Tamura Texture","wavelet","fourier",6,False,False]
feature_list["Tamura_Textures_Hue"] = ["Tamura Texture","Hue Transform","Empty Transform",6,True,False]
feature_list["Tamura_Textures_Wavelet"] = ["Tamura Texture","wavelet","Empty Transform",6,False,False]
feature_list["Tamura_Textures_Edge_Wavelet"] = ["Tamura Texture","edge","wavelet",6,False,False]
feature_list["Tamura_Textures_Fourier_Wavelet"] = ["Tamura Texture","fourier","wavelet",6,False,False]

#Zernike Coeffivients
feature_list["Zernike_Coefficients"] = ["Zernike Coefficients","Empty Transform","Empty Transform",72,False,False]
feature_list["Zernike_Coefficients_Chebyshev"] = ["Zernike Coefficients","chebyshev","Empty Transform",72,False,False]
feature_list["Zernike_Coefficients_Hue_Chebyshev"] = ["Zernike Coefficients","Hue Transform","chebyshev",72,True,False]
feature_list["Zernike_Coefficients_Color"] = ["Zernike Coefficients","wndchrmcolor","Empty Transform",72,True,False]
feature_list["Zernike_Coefficients_Edge"] = ["Zernike Coefficients","edge","Empty Transform",72,False,False]
feature_list["Zernike_Coefficients_Fourier"] = ["Zernike Coefficients","fourier","Empty Transform",72,False,False]
feature_list["Zernike_Coefficients_Edge_Fourier"] = ["Zernike Coefficients","edge","fourier",72,False,False]
feature_list["Zernike_Coefficients_Hue_Fourier"] = ["Zernike Coefficients","Hue Transform","fourier",72,True,False]
feature_list["Zernike_Coefficients_Wavelet_Fourier"] = ["Zernike Coefficients","wavelet","fourier",72,False,False]
feature_list["Zernike_Coefficients_Hue"] = ["Zernike Coefficients","Hue Transform","Empty Transform",72,True,False]
feature_list["Zernike_Coefficients_Wavelet"] = ["Zernike Coefficients","wavelet","Empty Transform",72,False,False]
feature_list["Zernike_Coefficients_Edge_Wavelet"] = ["Zernike Coefficients","edge","wavelet",72,False,False]

