#!/usr/bin/env python
""" Print all the usernames to the console. """


import os
import sys
import tgscheduler
from argparse import ArgumentParser

from paste.deploy import appconfig
from bq.config.environment import load_environment
from bq.core import model

from bq.module_service.controllers import MexRunner

def load_config(filename):
    conf = appconfig('config:' + os.path.abspath(filename))
    load_environment(conf.global_conf, conf.local_conf)

def parse_args():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("conf_file", help="configuration to use")
    return parser.parse_args()

def main():
    args = parse_args()
    load_config(args.conf_file)
    
    tgscheduler.start_scheduler()
    mexrunner = MexRunner('http://loup.ece.ucsb.edu:9090')


    tgscheduler.add_interval_task(interval=30,
                                  action=mexrunner.process_pending,
                                  initialdelay=10)

if __name__ == '__main__':
    sys.exit(main())
